/** Structural guard for L4 model/mode/workspace extraction. */
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source = (path: string) => readFileSync(new URL(`../src/dsh-adapter/${path}`, import.meta.url), 'utf8')
const root = source('channel.ts')
const model = source('channel/model-actions.ts')
const switchAction = source('channel/model-switch.ts')
const mode = source('channel/mode-actions.ts')
const workspace = source('channel/workspace-actions.ts')

assert.match(root, /createModelActions\(/u)
assert.match(root, /createModelSwitchAction\(/u)
assert.match(root, /createModeActions\(/u)
assert.match(root, /createWorkspaceActions\(/u)
assert.doesNotMatch(root, /async switchModel\(/u, 'model switch transaction belongs to channel/model-switch.ts')
assert.doesNotMatch(root, /async switchPreset\(/u, 'preset switch belongs to channel/model-actions.ts')
assert.doesNotMatch(root, /const foldPlanActive/u, 'mode folds belong to channel/mode-actions.ts')
assert.doesNotMatch(root, /async switchWorkspace\(/u, 'workspace switch belongs to channel/workspace-actions.ts')
assert.match(model, /let effortLevelsGeneration = 0/u)
assert.match(model, /captureEffort/u, 'every effort request captures route, binding, and operation')
assert.match(model, /effortCurrent\(capture\)/u, 'effort completion validates its capture before writes')
assert.match(model, /generation !== effortLevelsGeneration/u, 'effort metadata completion remains generation-fenced')
assert.match(model, /modelNodeCache\.generation/u, 'model completion cache remains generation-fenced')
assert.match(model, /writeEffortPref/u)
assert.match(model, /switchPreset/u)
assert.match(model, /const targetAgent = deps\.agent\(\)/u, 'preset recompose binds the original agent')
assert.match(model, /const targetSession = targetAgent\.session/u, 'preset recompose binds the original session')
assert.match(model, /if \(!current\(\)\) return false/u, 'preset completion is fenced before facts and preferences')
assert.match(switchAction, /await deps\.settleCompaction\(\)/u, 'compaction settles before model fork snapshot')
assert.match(switchAction, /deps\.binding\.prepare/u)
assert.match(switchAction, /deps\.binding\.adopt/u)
assert.match(switchAction, /writeModelPref/u)
assert.match(mode, /prePlanModes/u)
assert.match(mode, /approval\/policy/u)
assert.match(mode, /onSessionEvent/u)
assert.doesNotMatch(workspace, /state\.cwd = target\.cwd/u, 'workspace target is not speculatively published')
assert.match(workspace, /deps\.newSession\(\{ cwd: target\.cwd, displayCwd:/u, 'workspace uses the typed guarded target seam')
assert.match(workspace, /try \{[\s\S]*await deps\.newSession/u, 'workspace handles new-session rejection without publication')
console.log('verify:model-mode-workspace-extraction OK')
