/** Explicit in-process UI method inventory; never a wire protocol.
 * Queries that warm caches or publish notices remain effectful.
 */
import type { ChannelUi } from '../ports/channel-ui.js'
export type { ChannelUi } from '../ports/channel-ui.js'
import type { HostEffectClass } from '../ports/owner.js'

type MethodKeys<T> = { [K in keyof T]: T[K] extends (...args: never[]) => unknown ? K : never }[keyof T]
export type ChannelPreferences = Pick<ChannelUi,
  | 'setDiffLayout' | 'setThinkingFold' | 'setToolBackground' | 'setScrollGutter'
  | 'setPageMargin' | 'setFoldTerminalCommand' | 'setPromptSessionLabel'
  | 'setExpandEditor' | 'setSmoothStreaming' | 'setStatusBar' | 'setWhale' | 'setMinimal'
>
export const CHANNEL_UI_EFFECTS = Object.freeze({
  'setDiffLayout': 'mutate',
  'setThinkingFold': 'mutate',
  'setToolBackground': 'mutate',
  'setScrollGutter': 'mutate',
  'setPageMargin': 'mutate',
  'setFoldTerminalCommand': 'mutate',
  'setPromptSessionLabel': 'mutate',
  'setExpandEditor': 'mutate',
  'setSmoothStreaming': 'mutate',
  'setStatusBar': 'mutate',
  'setWhale': 'mutate',
  'setMinimal': 'mutate',
  'commandCompletions': 'mutate',
  'runExternalCommand': 'mutate',
  'openPluginScene': 'mutate',
  'closePluginScene': 'mutate',
  'sideQuestion': 'mutate',
  'stageImage': 'mutate',
  'submit': 'mutate',
  'steer': 'mutate',
  'removePending': 'mutate',
  'cancel': 'mutate',
  'interruptAndDeliver': 'mutate',
  'rewindTo': 'mutate',
  'promptRewind': 'mutate',
  'buildSessionTree': 'mutate',
  'rewindToNode': 'mutate',
  'forkSession': 'mutate',
  'resumeTo': 'mutate',
  'newSession': 'mutate',
  'listWorkspaces': 'read-only',
  'resolveWorkspace': 'mutate',
  'switchWorkspace': 'mutate',
  'renameWorkspace': 'mutate',
  'workspaceCommands': 'read-only',
  'runWorkspaceCommand': 'mutate',
  'switchModel': 'mutate',
  'listEfforts': 'mutate',
  'setEffort': 'mutate',
  'cycleMode': 'mutate',
  'permissionPresets': 'read-only',
  'listPresets': 'read-only',
  'switchPreset': 'mutate',
  'clear': 'mutate',
  'loadOlder': 'mutate',
  'notify': 'mutate',
  'setActivityFrames': 'mutate',
  'listModels': 'read-only',
  'listProviders': 'read-only',
  'invalidateModelCompletion': 'mutate',
  'listSkills': 'read-only',
  'describeCredential': 'read-only',
  'balanceInfo': 'mutate',
  'providerSetup': 'read-only',
  'oauthProviderStatuses': 'read-only',
  'settingsHost': 'read-only',
  'settingsSections': 'read-only',
  'subscribeSettingsSections': 'subscribe',
  'listFileCandidates': 'read-only',
  'listFiles': 'read-only',
  'listSessions': 'read-only',
  'previewSession': 'read-only',
  'setResumeTarget': 'mutate',
  'renameSession': 'mutate',
  'setSessionColor': 'mutate',
  'recapRecent': 'mutate',
  'deleteSession': 'mutate',
  'renameSessionTo': 'mutate',
  'compact': 'mutate',
  'pushLocal': 'mutate',
  'mcpStatus': 'read-only',
  'exportSession': 'mutate',
  'initWorkspace': 'mutate',
  'doctorInfo': 'read-only',
  'pluginsInfo': 'mutate',
  'listSubagents': 'read-only',
  'agentViewRows': 'read-only',
  'subscribeAgentView': 'subscribe',
  'dispatchBackgroundAgent': 'mutate',
  'stopBackgroundAgent': 'mutate',
  'attachToAgent': 'mutate',
  'peekAgentSession': 'read-only',
  'backgroundCurrent': 'mutate',
  'replyToAgent': 'mutate',
  'traceEvents': 'read-only',
  'subscribe': 'subscribe'
} satisfies Record<MethodKeys<ChannelUi>, HostEffectClass>)

export const CHANNEL_UI_PROPERTIES = [
  'version',
  'rows',
  'status',
  'sessionTitle',
  'sessionColor',
  'agentId',
  'agentBindingGeneration',
  'autoRecapOnOpen',
  'model',
  'provider',
  'configuredProvider',
  'configuredModel',
  'configuredPreset',
  'configuredActivityFrames',
  'configuredLang',
  'tokens',
  'cwd',
  'displayCwd',
  'gitBranch',
  'working',
  'cancelPending',
  'spinnerMode',
  'responseChars',
  'activeToolCount',
  'turnStart',
  'lastUserText',
  'notifications',
  'contextWindow',
  'reasoningEffort',
  'effortLevels',
  'lastUsage',
  'tps',
  'tpsSamples',
  'workingActivity',
  'activityFrames',
  'diffLayout',
  'thinkingFold',
  'toolBackground',
  'scrollGutter',
  'pageMargin',
  'foldTerminalCommand',
  'promptSessionLabel',
  'expandEditor',
  'smoothStreaming',
  'statusBar',
  'whale',
  'minimal',
  'activityEnabled',
  'contextBarEnabled',
  'goal',
  'todos',
  'loadedContext',
  'pending',
  'commandList',
  'pluginScene',
  'contextSegments',
  'subagents',
  'subagentControl',
  'backgroundJobs',
  'jobControl',
  'mode',
  'modeIndex',
  'agentPreset'
] as const satisfies readonly (keyof ChannelUi)[]

// Both inventories are exhaustive: adding a public property is a compile error
// until its runtime read projection is deliberately classified.
type PropertyKeys = Exclude<keyof ChannelUi, MethodKeys<ChannelUi>>
const allProperties: Exclude<PropertyKeys, typeof CHANNEL_UI_PROPERTIES[number]> extends never ? true : never = true
void allProperties
